### ISSUE TITLE
Chests/Shrines/Teleporter/Items not generating with TILER2 Enabled

### ISSUE THREAD

**Issue by Austinvonmonkeybutt** [ThinkInvis/RoR2-TILER2#19] opened 2021-04-13 05:07 UTC
I apologize if this is not up to date with the anniversary update, however ClassicItems mentions compatibility stuff for it and both mods were updated post anniversary, and i am assuming that they are up to date. I am currently attempting to run Classic Items by itself, so the only mods i am running when the issue occurs are bepinexpack r2api,  HookGenPatcher, and TILER2, sometimes classic items,   I am using the thunderstore mod manager.

On any run where i have TILER2 active, one of two issues occurs, the most common of which is that no objects generate. Enemies spawn, and the newt thing spawns, but no shrines, no chests, and no teleporter. Occasionally, i'll get a run where these items do generate, however when i open a chest it plays the chest opening animation, but no item drops 

I have tried this with multiple characters, after restarting the game multiple times, and with or without classic items, it happens in every run for me. The log is below, please let me know if there is something that can be done. i did see someone else had this issue and had a bunch of other mods, but i'm having this issue and i only have the prerequisiste ones

[Message:   BepInEx] BepInEx 5.4.9.0 - Risk of Rain 2
[Info   :   BepInEx] Running under Unity v2018.4.16.15133130
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.HookGenPatcher 1.1.0.0]
[Info   :   BepInEx] 2 patcher plugins loaded
[Info   :   Console] [MonoMod] 
[Info   :   Console] Reading input file into module.
[Info   :HookGenPatcher] Starting HookGenerator
[Info   :HookGenPatcher] Done.
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Debug  :   BepInEx] Skipping loading C:\Users\Austin\AppData\Roaming\Thunderstore Mod Manager\DataFolder\RiskOfRain2\profiles\Mods\BepInEx\plugins\tristanmcpherson-R2API\R2API\._R2API.dll because it's not a valid .NET assembly. Full error: Format of the executable (.exe) or library (.dll) is invalid.
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [R2API 3.0.13]
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.UnitySystemConsoleRedirector.Redirect
[Debug  :     R2API] DifficultyAPI has no static method registered for LoadCheck
[Debug  :     R2API] DirectorAPI has no static method registered for LoadCheck
[Debug  :     R2API] DotAPI has no static method registered for LoadCheck
[Debug  :     R2API] EffectAPI has no static method registered for LoadCheck
[Debug  :     R2API] EliteAPI has no static method registered for LoadCheck
[Debug  :     R2API] InteractablesAPI has no static method registered for LoadCheck
[Debug  :     R2API] ItemDropAPI has no static method registered for LoadCheck
[Debug  :     R2API] LoadoutAPI has no static method registered for LoadCheck
[Debug  :     R2API] LobbyConfigAPI has no static method registered for LoadCheck
[Debug  :     R2API] OrbAPI has no static method registered for LoadCheck
[Debug  :     R2API] ProjectileAPI has no static method registered for LoadCheck
[Debug  :     R2API] SceneAssetAPI has no static method registered for LoadCheck
[Debug  :     R2API] SurvivorAPI has no static method registered for LoadCheck
[Debug  :     R2API] UnlockableAPI has no static method registered for LoadCheck
[Info   :     R2API] Enabling R2API Submodule: ArtifactAPI
[Info   :     R2API] Enabling R2API Submodule: BuffAPI
[Info   :     R2API] Enabling R2API Submodule: ItemAPI
[Info   :     R2API] Enabling R2API Submodule: LanguageAPI
[Info   :     R2API] Enabling R2API Submodule: PrefabAPI
[Info   :     R2API] Enabling R2API Submodule: ResourcesAPI
[Info   :     R2API] Enabling R2API Submodule: CommandHelper
[Info   :     R2API] Enabling R2API Submodule: ILLine
[Info   :     R2API] Enabling R2API Submodule: NetworkingAPI
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.CharacterModel.UpdateMaterials
[Debug  :     R2API] Hook added by assembly:  for: RoR2.CharacterModel.UpdateMaterials
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.ItemDisplayRuleSet.Init
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.Language.GetLocalizedStringByToken
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.Language.TokenIsRegistered
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.Console.InitConVars
[Debug  :     R2API] Hook added by assembly: R2API.dll for: System.Diagnostics.StackTrace.AddFrames
[Debug  :     R2API] Hook added by assembly:  for: System.Diagnostics.StackTrace.AddFrames
[Debug  :     R2API] ArtifactAPI has no static method registered for Load
[Debug  :     R2API] BuffAPI has no static method registered for Load
[Debug  :     R2API] ItemAPI has no static method registered for Load
[Debug  :     R2API] LanguageAPI has no static method registered for Load
[Debug  :     R2API] PrefabAPI has no static method registered for Load
[Debug  :     R2API] ResourcesAPI has no static method registered for Load
[Debug  :     R2API] CommandHelper has no static method registered for Load
[Debug  :     R2API] ILLine has no static method registered for Load
[Debug  :     R2API] NetworkingAPI has no static method registered for Load
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.DisableIfGameModded.OnEnable
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.SteamworksLobbyDataGenerator.RebuildLobbyData
[Debug  :     R2API] Hook added by assembly:  for: RoR2.SteamworksLobbyDataGenerator.RebuildLobbyData
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.RoR2Application+<>c.<LoadGameContent>b__57_1
[Debug  :     R2API] Hook added by assembly:  for: RoR2.RoR2Application+<>c.<LoadGameContent>b__57_1
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.RoR2Content.LoadStaticContentAsync
[Info   :   BepInEx] Loading [TILER2 4.0.2]
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.Run.Start
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.Inventory.GetItemCount
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.CostTypeCatalog+LunarItemOrEquipmentCostTypeHelper.IsAffordable
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.CostTypeCatalog+LunarItemOrEquipmentCostTypeHelper.PayCost
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.CostTypeCatalog+LunarItemOrEquipmentCostTypeHelper.PayOne
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.Inventory.HasAtLeastXTotalItemsOfTier
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.Inventory.GetTotalItemCountOfTier
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.ItemStealController+StolenInventoryInfo.StealItem
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.RunReport.Generate
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.ScrapperController.BeginScrapping
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.ShrineCleanseBehavior.CleanseInventoryServer
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.ShrineCleanseBehavior.InventoryIsCleansable
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.Util.GetItemCountForTeam
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.PickupPickerController.SetOptionsFromInteractor
[Debug  :     R2API] Hook added by assembly:  for: RoR2.PickupPickerController.SetOptionsFromInteractor
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.UI.ItemInventoryDisplay.UpdateDisplay
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.UI.ItemInventoryDisplay.OnInventoryChanged
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.CostTypeCatalog+<>c.<Init>g__PayCostItems|5_1
[Debug  :     R2API] Hook added by assembly:  for: RoR2.CostTypeCatalog+<>c.<Init>g__PayCostItems|5_1
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.Util.IsPrefab
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.RoR2Application.Update
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.Networking.GameNetworkManager.Disconnect
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.PickupCatalog.Init
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.UI.LogBook.LogBookController.BuildPickupEntries
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.Run.BuildDropTable
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.Networking.GameNetworkManager.OnServerAddPlayerInternal
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.CharacterBody.RecalculateStats
[Debug  :     R2API] Hook added by assembly:  for: RoR2.CharacterBody.RecalculateStats
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.DirectorCore.TrySpawnObject
[Debug  :     R2API] Hook added by assembly:  for: RoR2.DirectorCore.TrySpawnObject
[Debug  :     R2API] Hook added by assembly: TILER2.dll for: RoR2.OccupyNearbyNodes.OnSceneDirectorPrePopulateSceneServer
[Message:   BepInEx] Chainloader startup complete
[Info   :   Console] Facepunch.Steamworks Unity: WindowsPlayer
[Info   :   Console] Facepunch.Steamworks Os: Windows
[Info   :   Console] Facepunch.Steamworks Arch: x64
[Info   :   Console] Searching for compatible XInput library...
[Info   :   Console] Found Xinput1_4.dll.
[Info   : Unity Log] Initializing Mod System...
[Info   : Unity Log] Mod System initialized.
[Info   : Unity Log] WwiseUnity: Sound engine initialized successfully.
[Info   : Unity Log] Setting current language to "en"
[Info   : Unity Log] Launch Parameters: 
  arg[0]="D:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2.exe"
  arg[1]="--doorstop-enable"
  arg[2]="true"
  arg[3]="--doorstop-target"
  arg[4]="C:/Users/Austin/AppData/Roaming/Thunderstore Mod Manager/DataFolder/RiskOfRain2/profiles/Mods/BepInEx/core/BepInEx.Preloader.dll"

[Info   : Unity Log] Could not load config /Config/config.cfg: Could not find file "D:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\config.cfg"
[Info   : Unity Log] Could not load config /Config/autoexec.cfg: Could not find file "D:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\autoexec.cfg"
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.Run.BuildDropTable
[Debug  :     R2API] Hook added by assembly:  for: RoR2.Run.BuildDropTable
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.Artifacts.MonsterTeamGainsItemsArtifactManager.GenerateAvailableItemsSet
[Debug  :     R2API] Hook added by assembly:  for: RoR2.Artifacts.MonsterTeamGainsItemsArtifactManager.GenerateAvailableItemsSet
[Debug  :     R2API] Hook added by assembly: R2API.dll for: RoR2.BossGroup.DropRewards
[Debug  :     R2API] Hook added by assembly:  for: RoR2.BossGroup.DropRewards
[Info   : Unity Log] LoadContentPacks() start
[Info   : Unity Log] Active scene changed from  to loadingbasic
[Debug  :    TILER2] Stage ended; applying 0 deferred config changes...
[Info   : Unity Log] Loaded scene loadingbasic loadSceneMode=2
[Info   :     R2API] [NetworkCompatibility] Adding to the networkModList : 
[Info   :     R2API] com.bepis.r2api;3.0.13
[Info   :     R2API] com.ThinkInvisible.TILER2;4.0.2
[Info   : Unity Log] Setting current language to "en"
[Info   : Unity Log] LoadContentPacks() end
[Info   : Unity Log] Game content load completed in 5871ms.
[Info   : Unity Log] [RoR2.EntityStateCatalog] ApplyEntityStateConfiguration(EntityStates.MoonElevator.ReturnToBase (RoR2.EntityStateConfiguration)) failed: state type is null.
[Info   : Unity Log] [RoR2.EntityStateCatalog] ApplyEntityStateConfiguration(EntityStates.MoonElevator.TravelToEnd (RoR2.EntityStateConfiguration)) failed: state type is null.
[Info   : Unity Log] [RoR2.EntityStateCatalog] ApplyEntityStateConfiguration(EntityStates.MoonElevator.WaitAtTop (RoR2.EntityStateConfiguration)) failed: state type is null.
[Info   : Unity Log] [RoR2.Language] Setting current language to "en"
[Info   : Unity Log] Attempting to load user profile /UserProfiles/50a9de5e-3c65-4901-a79c-aacf8a70e8ef.xml
[Info   : Unity Log] stream.Length=122083
[Info   : Unity Log] Attempting to load user profile /UserProfiles/6ef7c232-efab-4d31-ac16-0fedd161caae.xml
[Info   : Unity Log] stream.Length=142270
[Info   : Unity Log] Attempting to load user profile /UserProfiles/c7b9946b-423e-49c2-bfb6-ae9f74ee6649.xml
[Info   : Unity Log] stream.Length=118389
[Info   : Unity Log] Attempting to load user profile /UserProfiles/eb089a7d-88d1-42c3-bd91-4ecaa3013698.xml
[Info   : Unity Log] stream.Length=139440
[Info   : Unity Log] Unloaded scene loadingbasic
[Info   : Unity Log] Active scene changed from  to splash
[Debug  :    TILER2] Stage ended; applying 0 deferred config changes...
[Info   : Unity Log] Loaded scene splash loadSceneMode=Single
[Info   : Unity Log] Setting offline scene to intro
[Info   : Unity Log] Unloaded scene splash
[Info   : Unity Log] Active scene changed from  to intro
[Debug  :    TILER2] Stage ended; applying 0 deferred config changes...
[Info   : Unity Log] Loaded scene intro loadSceneMode=Single
[Info   : Unity Log] Setting offline scene to title
[Info   : Unity Log] Unloaded scene intro
[Info   : Unity Log] Active scene changed from  to title
[Debug  :    TILER2] Stage ended; applying 0 deferred config changes...
[Info   : Unity Log] Loaded scene title loadSceneMode=Single
[Info   : Unity Log] GameNetworkManager.desiredHost={ hostType=Self listen=False maxPlayers=4 }
[Info   :     R2API] Server Handlers registered
[Info   :     R2API] Client Handlers registered
[Info   : Unity Log] Unloaded scene title
[Info   : Unity Log] Active scene changed from  to lobby
[Debug  :    TILER2] Stage ended; applying 0 deferred config changes...
[Info   : Unity Log] Loaded scene lobby loadSceneMode=Single
[Info   : Unity Log] gridColumns=8,totalElements=11,gridRows=2,maxEntryCount=16
[Info   : Unity Log] Adding local player controller 0 on connection hostId: -1 connectionId: 0 isReady: False channel count: 0
[Info   : Unity Log] GameNetworkManager.AddPlayerInternal(conn=hostId: -1 connectionId: 0 isReady: False channel count: 0, playerControllerId=0, extraMessageReader=NetBuf sz:251 pos:251
[Info   : Unity Log] OnClientSceneChanged networkSceneName=lobby currentSceneName=lobby
[Error  : Unity Log] A connection has already been set as ready. There can only be one.
[Info   : Unity Log] Player 0 already added, aborting.
[Info   : Unity Log] Could not load config /Config/server_pregame.cfg: Could not find file "D:\SteamLibrary\steamapps\common\Risk of Rain 2\Risk of Rain 2_Data\Config\server_pregame.cfg"
[Info   : Unity Log] Attempting to generate PreGameVoteController for Austinvonmonkeybutt
[Info   : Unity Log] PreGameRuleVoteController.ClientTransmitVotesToServer()
[Info   : Unity Log] Received vote from Austinvonmonkeybutt
[Info   : Unity Log] Accepting vote from Austinvonmonkeybutt
[Info   : Unity Log] <style=cEvent>Austinvonmonkeybutt connected.</color>
[Error  : Unity Log] MissingMethodException: void R2API.ItemDropAPI.AddEquipment(RoR2.EquipmentIndex[])
Stack trace:
DMD<>?1091331072.Hook<RoR2.Run::BuildDropTable>?-912566528 (RoR2.Run ) (at <eab20cd3a18c438ca49c497aaec367f6>:IL_0014)
DMD<Start>?1091331072._RoR2_Run::Start (RoR2.Run this) (at <b0453b3c5ce84376aac2b7e0648c8e03>:IL_0102)
DMD<>?1091331072.Trampoline<RoR2.Run::Start>?284147712 (RoR2.Run ) (at <e81cf70dc876496bb9998c027954a68b>:IL_0020)
TILER2.T2Module.On_RunStart (On.RoR2.Run+orig_Start orig, RoR2.Run self) (at <c1d98dc207bd479faaa085987e695a1a>:IL_0000)
DMD<>?1091331072.Hook<RoR2.Run::Start>?-153833984 (RoR2.Run ) (at <cd44868007694cacb454c4cb87cca120>:IL_000A)

[Info   : Unity Log] Unloaded scene lobby
[Info   : Unity Log] Active scene changed from  to blackbeach2
[Debug  :    TILER2] Stage ended; applying 0 deferred config changes...
[Info   : Unity Log] Loaded scene blackbeach2 loadSceneMode=Single
[Info   : Unity Log] OnClientSceneChanged networkSceneName=blackbeach2 currentSceneName=blackbeach2
[Info   : Unity Log] Client ready.
[Info   : Unity Log] Player 0 already added, aborting.
[Info   : Unity Log] Spending 180 credits on interactables...
[Error  : Unity Log] ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: Range cannot have size of zero.
Stack trace:
Xoroshiro128Plus.RangeUInt32Uniform (System.UInt32 maxExclusive) (at <5b58f7c3855e4315866ebf9466348c23>:IL_0003)
Xoroshiro128Plus.RangeInt (System.Int32 minInclusive, System.Int32 maxExclusive) (at <5b58f7c3855e4315866ebf9466348c23>:IL_0000)
Xoroshiro128Plus.NextElementUniform[T] (T[] array) (at <5b58f7c3855e4315866ebf9466348c23>:IL_0000)
RoR2.Artifacts.MonsterTeamGainsItemsArtifactManager.GrantMonsterTeamItem () (at <6e882c67227c45d48048fa96336d8982>:IL_0060)
RoR2.Artifacts.MonsterTeamGainsItemsArtifactManager.EnsureMonsterTeamItemCount (System.Int32 itemCount) (at <6e882c67227c45d48048fa96336d8982>:IL_0002)
RoR2.Artifacts.MonsterTeamGainsItemsArtifactManager.EnsureMonsterItemCountMatchesStageCount () (at <6e882c67227c45d48048fa96336d8982>:IL_0005)
RoR2.Artifacts.MonsterTeamGainsItemsArtifactManager.OnPrePopulateSceneServer (RoR2.SceneDirector sceneDirector) (at <6e882c67227c45d48048fa96336d8982>:IL_0000)
RoR2.SceneDirector.Start () (at <6e882c67227c45d48048fa96336d8982>:IL_00EB)

[Error  : Unity Log] Object PodGroundImpact(Clone) (UnityEngine.GameObject) should not be instantiated by means other than EffectManager.SpawnEffect. This WILL result in an NRE!!! Use EffectManager.SpawnEffect or don't use EffectComponent!!!!!
[Info   : Unity Log] Spawn card cscLemurian (RoR2.CharacterSpawnCard) failed to spawn. Aborting cost procedures.
[Info   : Unity Log] Saved file "6ef7c232-efab-4d31-ac16-0fedd161caae.xml" (139248 bytes)
[Info   : Unity Log] Shutting down Steamworks...
[Info   : Unity Log] Shut down Steamworks.
[Info   :   Console] Rewired is not initialized. You must have an active and enabled Rewired Input Manager in the scene before calling any part of the Rewired API.
------- Rewired System Info -------
Unity version: 2018.4.16f1
Rewired version: 1.1.21.3.U2018
Platform: Windows
Using Unity input: False

[Info   :   Console] Rewired is not initialized. You must have an active and enabled Rewired Input Manager in the scene before calling any part of the Rewired API.
------- Rewired System Info -------
Unity version: 2018.4.16f1
Rewired version: 1.1.21.3.U2018
Platform: Windows
Using Unity input: False

[Info   : Unity Log] Transfered 2.8 monster credits from Director (UnityEngine.GameObject) to Director (UnityEngine.GameObject)

**Comment by sniggyfigbat** [comment] 2021-04-13 14:18
I'm having exactly the same issue.

**Comment by DragonTrainerBen** [comment] 2021-04-13 20:58
Same issue.
After starting the game first game, first stage always lacks chests, drones, teleporter etc. (cannot confirm nor deny newt spawn)
Successive games first stage's have empty chests, 3D printers without a shown item, teleporters don't drop items on boss kill. (Drones and turrets are there and fully functional) 
Second area so far always lacks chests, drones, teleporter etc.

- You can still acquire the "Fuel array" equipment if playing as a drop-pod survivor, still functional
- Abandoned Aqueduct still has pressure plates (and clay pots) while chests etc. are nonexistent.


[logoutput_1_vanilla.txt](https://github.com/ThinkInvis/RoR2-TILER2/files/6306690/logoutput_1_vanilla.txt)
Log 1: "Vanilla" (Commando, Rainstorm, no Artifacts)
   - Run 1: no chests, drones, teleporter etc. quit to menu.
   - Run 2: chests but no items, die to boss.
   - Run 3: 
      - Stage 1: chests but no items, no boss drop, 
      - Stage 2: no chests etc. quit to menu.

[logoutput_2_Sacrifice.txt](https://github.com/ThinkInvis/RoR2-TILER2/files/6306694/logoutput_2_Sacrifice.txt)
Log 2: "Sacrifice" (Huntress, Rainstorm, Artifact of Sacrifice)
   - Run 1: no drones, etc. no sacrifice drops, tested "Fuel array", works perfectly, self kill.
   - Run 2: 
      - Stage 1: drones etc. but no items, no sacrifice drops, no boss drop, 
      - Stage 2: no drones, etc. no sacrifice drops, found pressure plates, but couldn't activate both. quit to menu.

[logoutput_3_curiosity.txt](https://github.com/ThinkInvis/RoR2-TILER2/files/6306696/logoutput_3_curiosity.txt)
Log 3: "Curiosity" (Tried using w/ mods "spawnitems", "Artifact of Doom", and "Yeet")
   - "spawnitems" could not spawn items
   - "Artifact of Doom" can spawn items directly into inventory successfully (didn't test pool for "classicitems" items)
   - "Yeet" drops item, dropped item immediately disappears.

**Comment by ben-spargo** [comment] 2021-04-14 06:34
potentially tied to character and NRE that occurs with drop pod.

choosing Mul-T or Acrid, and i imagine any other character that doesn't use the pod results in things spawning and gameplay as intended.

**Comment by Austinvonmonkeybutt** [comment] 2021-04-14 06:36
I'll try that in a bit, if i can only play those 2 characters i will deal with it in the interrim

**Comment by ben-spargo** [comment] 2021-04-14 07:06
Well cancel that entirely. Just thought i double check and started a run with MUL-T... no spawns

**Comment by Austinvonmonkeybutt** [comment] 2021-04-14 07:07
that sucks, thanks for letting me know

**Comment by gojlus** [comment] 2021-04-14 22:02
+1 same issue. Seems like most of the item mods are currently non functioning. F.

**Comment by zantanzuken** [comment] 2021-04-15 11:03
having the same problem... it seems to be an issue directly with the TILER2 library itself, as having only it and no other mods attached causes the issues. aside from what everyone else says, the error itself appears to be that the library is stopping the director from placing items (at least in the first case) and making the drop pool empty (which causes chests in subsequent runs to drop nothing, enemies with sacrifice to drop nothing, as they have no pool to drop from)

**Comment by CrazyCookieBuddy** [comment] 2021-04-15 14:08
Yea, I'm having the exact same issue, same error as well

**Comment by Fornax42** [comment] 2021-04-15 15:19
Adding one more to the list of people having this issue, witht he same error.
I can confirm Newt Alters do still spawn by the way, but they are the only thing that does.

**Comment by ThinkInvis** [comment] 2021-05-03 02:05
This was just a case of "base game/R2API code changed and mine stayed put". Should be fixed now.
Related: https://github.com/ThinkInvis/RoR2-ClassicItems/issues/86

**Closed by ThinkInvis** 2021-05-03 02:05 UTC
